#!/usr/bin/env python3
"""
Download the four typefaces into public/fonts/ and write src/fonts.css.

Self-hosting keeps the experience off a third party — nothing render-blocking
from another origin — and lets the social card be generated with the real
typography rather than fallback serifs.

Only the `latin` subset is kept (it already covers the curly quotes, ellipses
and em dashes in the copy), and only the weights the design actually uses.

    python3 scripts/fetch-fonts.py
"""

import os
import re
import ssl
import urllib.request

UA = (
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
    '(KHTML, like Gecko) Chrome/120.0 Safari/537.36'
)

URL = (
    'https://fonts.googleapis.com/css2?'
    'family=Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400;1,600'
    '&family=Inter:wght@300;400;500;600;700'
    '&family=Roboto+Slab:wght@400;700;900'
    '&family=JetBrains+Mono:wght@400'
    '&display=swap'
)

KEEP_SUBSETS = {'latin'}
CA_BUNDLE = '/root/.ccr/ca-bundle.crt'


def fetch(url, binary=False):
    ctx = ssl.create_default_context(cafile=CA_BUNDLE) if os.path.exists(CA_BUNDLE) else None
    request = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(request, context=ctx, timeout=60) as response:
        return response.read() if binary else response.read().decode()


def main():
    os.makedirs('public/fonts', exist_ok=True)
    css = fetch(URL)
    blocks = re.findall(r'/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)

    faces, sizes = [], {}
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r'font-weight:\s*(\d+)', block).group(1)
        style = re.search(r'font-style:\s*(\w+)', block).group(1)
        remote = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)

        name = f"{family.replace(' ', '')}-{weight}{'i' if style == 'italic' else ''}.woff2"
        path = os.path.join('public/fonts', name)
        if name not in sizes:
            with open(path, 'wb') as handle:
                handle.write(fetch(remote, binary=True))
            sizes[name] = os.path.getsize(path)

        faces.append(block.replace(remote, f'/fonts/{name}').replace('src:', 'font-display: swap;\n  src:'))

    header = (
        '/* Generated by scripts/fetch-fonts.py — do not edit by hand.\n'
        '   Self-hosted so the experience never waits on a third party, and so the\n'
        '   social card renders in the real typefaces. */\n\n'
    )
    with open('src/fonts.css', 'w') as handle:
        handle.write(header + '\n\n'.join(faces) + '\n')

    print(f'{len(sizes)} files, {round(sum(sizes.values()) / 1024)} KB total')


if __name__ == '__main__':
    main()
